resource_types: []

resources:
- name: root
  type: git
  source:
    uri: https://github.com/jinsenglin/conci-working-dir-v3.git
    branch: master

jobs:
- name: demo job
  plan:
  - get: root
  - task: demo task
    file: root/ci/tasks/demo.yml
