---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jimlintw/grafana-builder
    tag: 2.0.0

inputs: []

outputs: []

params: {}

run:
  path: root/ci/scripts/build-grafana.sh
