---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: latest

inputs:
- name: root

outputs: []

params:
  secret:

run:
  path: root/ci/scripts/demo.sh
