---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: latest

inputs: []

outputs: []

params: {}

run:
    path: sh
    args:
    - -exec
    - |
      echo Hello World!
