---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: latest

inputs: []

outputs: []

params:
    shell: &shell sh

run:
    path: *shell
    args:
    - -exec
    - |
      echo Hello World!
